spring.application.name=Search-Service
server.port=8083


# Circuit Breaker Config

resilience4j.circuitbreaker.instances.File-Service.register-health-indicator=true
resilience4j.circuitbreaker.instances.File-Service.sliding-window-size=10
resilience4j.circuitbreaker.instances.File-Service.minimum-number-of-calls=2
resilience4j.circuitbreaker.instances.File-Service.failure-rate-threshold=20
resilience4j.circuitbreaker.instances.File-Service.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.File-Service.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.File-Service.automatic-transition-from-open-to-half-open-enabled=true

spring.cloud.openfeign.circuitbreaker.enabled=true